[project]
name = "psrt-ghsa-bot"
version = "0.1.0"
description = "GitHub bot for PSRT activities on GHSA"
readme = "README.md"
requires-python = ">=3.14.0"
dependencies = [
    "cvelib>=1.4.0",
    "githubkit[auth-app]>=0.13.5",
    "playwright>=1.55.0",
    "python-dotenv>=1.0.0",
]

[dependency-groups]
dev = [
    "mock>=5.2.0",
    "pytest>=8.4.2",
    "pytest-playwright>=0.7.1",
    "pytest-sugar>=1.1.1",
    "ruff>=0.14.3",
    "ty>=0.0.1a25",
]

[build-system]
requires = ["uv_build>=0.9.6,<0.10.0"]
build-backend = "uv_build"

[tool.ruff]
target-version = "py314"
src = ["src", "tests"]
line-length = 120
indent-width = 4

[tool.ruff.lint]
ignore = ["D203", "D213", "COM812"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"

[tool.ruff.lint.pydocstyle]
convention = "google"
